#!/bin/bash

git remote set-url origin https://mosleyj@cis3760.socs.uoguelph.ca/cis-3760-winter-2019/w19-section-2-group-1-project.git
git push
git remote set-url origin https://github.com/jamesmosley55/CIS3760
